[package]
name = "wgpu-renderer"
version = "0.1.0"
authors = ["Le_Charooo <Raphaelmoralibigras@outook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.6.0"
winit = "0.22.2"
